name: Cypress Cross-Browser + Mochawesome Report

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  cypress-tests:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        browser: [chrome, edge, firefox]
    runs-on: ubuntu-latest
    name: Run on ${{ matrix.browser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Clean previous Mochawesome reports
        run: npm run clean-reports

      - name: Run Cypress on ${{ matrix.browser }}
        run: |
          npx cypress run --browser ${{ matrix.browser }} \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true

      - name: Upload Mochawesome JSON (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-json-${{ matrix.browser }}
          path: cypress/reports/mochawesome/*.json

  merge-report:
    if: github.event.pull_request.merged == true
    needs: cypress-tests
    runs-on: ubuntu-latest
    name: Merge & Generate Mochawesome Report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: mochawesome-artifacts

      - name: Merge all JSON reports
        run: |
          mkdir -p cypress/reports/mochawesome
          find mochawesome-artifacts -name '*.json' -exec cp {} cypress/reports/mochawesome/ \;
          npx mochawesome-merge cypress/reports/mochawesome/*.json -o cypress/reports/mochawesome/mochawesome.json

      - name: Generate HTML report
        run: |
          npx marge cypress/reports/mochawesome/mochawesome.json -f index -o cypress/reports/final

      - name: Upload final Mochawesome HTML
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-html-report
          path: cypress/reports/final
