name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    name: Run Cypress Tests on ${{ matrix.browser }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests on ${{ matrix.browser }}
        run: |
          npx cypress run --browser ${{ matrix.browser }} --headless \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=false,json=true

      - name: Merge Mochawesome Reports
        if: ${{ matrix.browser == 'chrome' }}  # Only do this once
        run: |
          npx mochawesome-merge cypress/reports/mochawesome/*.json > mochawesome.json
          npx marge mochawesome.json -f index -o cypress/reports/final

      - name: Upload HTML Report
        if: ${{ matrix.browser == 'chrome' }}
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/final/index.html
